Lasso:
  aoi: "12"
  polarizations: ["VH", "VV"]

   # Filter
  kernel: 3
  iteration: 3
  eps: 3

  # Harmonics
  Harmonic_frequency: 365
  Harmonic_pairs: 4

  ## Directories
  dir_raw: /home/boka/Documents/AgrMapping/Sentinel/Aoi_{}/Raw
  dir_img: /home/boka/Documents/AgrMapping/Sentinel/Aoi_{}/Merged_new

  dir_ready: /home/boka/Documents/AgrMapping/Sentinel/Aoi_{}/Aoi_{}_{}_ready
  dir_meta: '{}/Meta_aoi{}.pkl'
  dir_out: /home/boka/Documents/AgrMapping/Sentinel/Aoi_12/Lasso/Coefs_Aoi{}_{}.tif

AWS:
  region: us-east-1
  access_key_id:
  secret_access_key:
  bucket: activemapper
  prefix: planet/
  prefix_label: labels_fix/
  score_prefix: classified-images/




