Lasso:
  aoi: "12"
  polarizations: ["VH", "VV"]

   # Filter
  kernel: 3
  iteration: 3
  eps: 3

  # Harmonics
  Harmonic_frequency: 365
  Harmonic_pairs: 4

  ## Directories
  dir_raw: /home/boka/Documents/AgrMapping/Sentinel/Aoi_{}/Raw
  dir_img: /home/boka/Documents/AgrMapping/Sentinel/Aoi_{}/Merged_new

  dir_ready: /home/boka/Documents/AgrMapping/Sentinel/Aoi_{}/Aoi_{}_{}_ready
  dir_meta: '{}/Meta_aoi{}.pkl'
  dir_out: /home/boka/Documents/AgrMapping/Sentinel/Aoi_{}/Lasso/Coefs_Aoi{}_{}.tif

Cluster:
  dir_data: /home/boka/Documents/AgrMapping/Sentinel
  data_col: dir_img

  # train
  dir_train: /home/boka/Documents/AgrMapping/Sentinel
  catalog_train: catalog_test_train.csv
  sample_rate: 0.003
  cluster_number: 20

  # predict
  ## provided modes are "single", "merge_row", and " merge_all"
  mode: merge_all
  dir_model: /home/boka/Documents/AgrMapping/Sentinel/model.sav
  dir_predict: /home/boka/Documents/AgrMapping/Sentinel/test_code
  fn_predict: kmean_{}.tif
  catalog_predict: catalog_test_predict.csv
  ## column in catalog specifying tile row indices, only applicable when mode is "merge_row"
  tilerow_index_col: tile_row

  # reclass
  dir_reclass: /home/boka/Documents/AgrMapping/Sentinel/test_reclass
  fn_reclass: reclass_{}.tif
  merge_reclassed: True
  reclass_values: [16]
  fn_merge: test_merged.tif

AWS:
  region: us-east-1
  access_key_id:
  secret_access_key:
  bucket: activemapper
  prefix: planet/
  prefix_label: labels_fix/
  score_prefix: classified-images/




